import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

/** The visible label every AI output carries. */
export function AiGeneratedLabel({ model, className }: { model?: string; className?: string }) {
  return (
    <span
      className={cn(
        "border-adv-llm/50 bg-adv-llm/10 text-foreground inline-flex max-w-full min-w-0 items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-semibold",
        className,
      )}
      title={model ? `AI-generated by ${model}` : undefined}
    >
      <Sparkles className="text-adv-llm size-3 shrink-0" aria-hidden />
      <span className="whitespace-nowrap">AI-generated</span>
      {model ? (
        <span className="min-w-0 truncate font-mono font-normal opacity-80">· {model}</span>
      ) : null}
    </span>
  );
}
